### ISSUE TITLE
Bug: Only dirty kernels can be spawned

### ISSUE THREAD

**Issue by felixeberhardt** [disaggr/smog#14]
Regardless of the parameters passed to smog, e.g. `./smog -t 2 -k d l`
This leads to:
`Creating 2 SMOG threads`
`  creating SMOG thread #0 with 16384 pages (0--16383)`
`  creating SMOG thread #1 with 16384 pages (16384--32767)`
`initialization finished, starting monitor`
`[0] d 214090 iterations at 213938 iterations/s, elapsed: 1000.71 ms, 26.1155 MiB/s, per iteration: 4674.25 nanoseconds`
`[1] d 2139159 iterations at 2.13764e+06 iterations/s, elapsed: 1000.71 ms, 260.942 MiB/s, per iteration: 467.806 nanoseconds`

**Comment by oaken-source** [comment]
should be fixed in 3feafffef3f37c7ddb938da02b33d98831301c10
