### ISSUE TITLE
Fast kernels suffer from the delay loop header at smog_delay=0

### ISSUE THREAD

**Issue by oaken-source** [disaggr/smog#6]
when the delay is set to zero, the header of the delay loop is still present and executed on each iteration. for fast kernels, such as linear_scan, this creates significant overhead. I tested this out in d3c6273e8b433adb648ac0a64bfe411298eb25eb and I measured about 5.8ns per item vs 4.4ns per item for the same call

`numactl -C 48,52 -m 8 ./smog -t 1 -k l -d 0 -M 100`

A possible workaround for this could be adding extra functions for the special case delay=0 that don't include the delay loop at all. an example how this could look is included in d3c6273e8b433adb648ac0a64bfe411298eb25eb

**Comment by felixeberhardt** [comment]
Fixed with unhinged kernel funcitonality
